### PR TITLE
backport to rhel7-branch spokes/category API

### PR DESCRIPTION
**Pull request by alikins**

### CODE REVIEW

**Comment by alikins** [comment]
Backport of hello world example to the rhel7-branch of anaconda/initial-setup.

Note: This branch only works on rhel7, so would need to live in a branch instead of master. 

I didn't try to abstract master to work with both, but that may be possible.  I suspect some
module import workarounds could handle the pyanaconda.ui.gui.categories -> pyanaconda.ui.categories changes. No idea if that would be worth the effort though.

**Comment by vpodzime** [comment]
Sorry for a late reply, I've been quite busy with other things lately. This generally looks good to me, but I think we could fork the rhel7-branch from master and revert the commit 450d1c38c1814667bb625175fa4c9e4809867114 instead. What do you think about that?

**Comment by VladimirSlavik** [comment]
Hello @alikins , is this still something you want to work on? Sorry for this - the installer team has changed rather dramatically since you submitted this, which is why this probably lay untouched so long.

For starters, I have trouble interpreting what this is. Am I correct that you changed the hello world addon, such that it works with initial setup for RHEL 7? If so, you definitely have the wrong base branch (master), it should be `rhel7-branch`.

**Comment by alikins** [comment]
I'm no longer working on anything anaconda related so I'll close this. In the past I was working on some of the rhn/rhsm anaconda/initial-setup screens for RHEL7 but not now.

**Pull request closed without merging**
